src/WsunBundle/Entity/Role.php
<?php

namespace WsunBundle\Entity;

use Symfony\Component\Security\Core\Role\RoleInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="roles")
 */
class Role implements RoleInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="nombre", type="string", length=255)
     */
    protected $name;
    
    /**
     * @ORM\Column(name="detalle", type="string", length=255)
     */
    protected $detalle;
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * Set detalle
     *
     * @param string $detalle
     */
    public function setDetalle($detalle)
    {
        $this->detalle = $detalle;
    }

    /**
     * Get detalle
     *
     * @return string
     */
    public function getDetalle()
    {
        return $this->detalle;
    }

    public function getRole() {
        return $this->getName();
    }

    public function __toString() {
        return $this->getRole();
    }
}

src/WsunBundle/Form/PedidoType.php
<?php

namespace WsunBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
class PedidoType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $rol=$options[0];
        /*$pedidoCodigo = $em->getRepository('WsunBundle:Pedido')
            ->findOneBy(
                array(),
                array('id' => 'DESC')
            );
        $codigo=$pedidoCodigo->getCodigoPedido();
        $codigo=$codigo+1;*/

        $builder->add('codigoPedido',TextType::class,array('label'=>'Codigo:'),array('class'=>'form-control'));
        $builder->add('fechaCreacion', DateType::class,array('label'=>'Fecha registro:'));
                //->add('idDepartamento')
        if($rol =='ROLE_ACEPTAR_PEDIDO')
        {
        $builder->add('estadoPedido',  CheckboxType::class ,array('label'=>'Activar:','required' => false));
        $builder->add('updatedBy',HiddenType::class);
        }
        $builder->add('ordenSap');   
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'WsunBundle\Entity\Pedido','rol' 
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'wsunbundle_pedido';
    }


}

src/WsunBundle/Controller/PedidoController.php
<?php

namespace WsunBundle\Controller;

use WsunBundle\Entity\Pedido;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Dompdf\Dompdf;
/**
 * @Security("has_role('ROLE_USER')")
 */
class PedidoController extends Controller
{
    private $session;
    public function __construct() {
        $this->session=new Session();
    }
	/**
     * Lists all pedido entities.
     *
     */
    public function indexAction(Request $request)
    {
        
        $user = $this->getUser();
        
            $ActivarNuevo=0;
             $admin=0;
            if(in_array('ROLE_USER', $this->getUser()->getRoles())){
                $ActivarNuevo=1;    
            }else if(in_array('ROLE_ADMIN', $this->getUser()->getRoles())){
                $admin=1;
            }
			$idEmpresa=0;
			
			if (!is_null($user->getDepartamento())){
				$idEmpresa=$user->getDepartamento()->getIdEmpresa()->getId();
			}
			
       $idUser=$this->getUser()->getId();
	  
        /* @var $qb \Doctrine\ORM\QueryBuilder */
        $qb = $this->getDoctrine()->getManager()->createQueryBuilder();
        $qb->from('WsunBundle:Pedido', 'ped');
        $qb->select('e.id,e.nombreEmp,ped.codigoPedido');
        $qb->innerJoin('ped.idUsuario', 'u');
        $qb->innerJoin('u.departamento', 'dpt');
        $qb->innerJoin('dpt.idEmpresa', 'e');
        if($admin!= '1' and $idEmpresa>0){
        $qb->andWhere('e.id = :id');
		$qb->andWhere('ped.idUsuario = :idus');    
        $qb->setParameter('idus', $idUser);
        $qb->setParameter('id', $idEmpresa);
        }
		
        $qb->addGroupBy('e.id,e.nombreEmp,ped.codigoPedido');
        $qb->addOrderBy('e.nombreEmp', 'ASC');

        $empresa = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
       

        //$em = $this->getDoctrine()->getManager();
       //$pedidos = $em->getRepository('WsunBundle:Pedido')->findAll();
        /* @var $qb \Doctrine\ORM\QueryBuilder */
        $qb = $this->getDoctrine()->getManager()->createQueryBuilder();
        $qb->from('WsunBundle:Pedido', 'ped');
        $qb->select('e.id as idEmpresa,ped.id, ped.fechaCreacion, ped.codigoPedido,ped.estadoPedido, dpt.nombreDep,e.nombreEmp');
        $qb->innerJoin('ped.idUsuario', 'u');
        $qb->innerJoin('u.departamento', 'dpt');
        $qb->innerJoin('dpt.idEmpresa', 'e');
		if ($ActivarNuevo==1 and $idEmpresa>0 ){
        $qb->andWhere('e.id = :id');
		$qb->andWhere('ped.idUsuario = :idus');    
        $qb->setParameter('idus', $idUser);
        $qb->setParameter('id', $idEmpresa);
		}
        $qb->addOrderBy('ped.codigoPedido', 'DESC');
        
		$pedidos = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
		
        $paginator = $this->get('knp_paginator');
        $limite = $this->container->getParameter('limitePaginacion');
        $pagination = $paginator->paginate(
                $pedidos, 
                $request->query->getInt('page', 1),
                $limite
        );
		
        return $this->render('WsunBundle:pedido:index.html.twig', 
            array('pagination' => $pagination,'empresa'=>$empresa,'activarNuevo'=>$ActivarNuevo));

    }
    public function consultaPorEmpresaAction(Request $request) {
        $id=$request->get('id'); 
        $estado=$request->get('estado');
        /* @var $qb \Doctrine\ORM\QueryBuilder */
        $qb = $this->getDoctrine()->getManager()->createQueryBuilder();
        $qb->from('WsunBundle:Pedido', 'ped');
        $qb->select('e.id as idEmpresa,ped.id, ped.codigoPedido,ped.fechaCreacion,ped.estadoPedido, dpt.nombreDep,e.nombreEmp');
        $qb->innerJoin('ped.idUsuario', 'u');
        $qb->innerJoin('u.departamento', 'dpt');
        $qb->innerJoin('dpt.idEmpresa', 'e');
        if ($estado == '1') {
                $qb->andWhere('ped.estadoPedido = :estado');
                $qb->setParameter('estado', '1');
        } elseif (empty($estado)) {
                $qb->andWhere('ped.estadoPedido IS NULL');
                // $qb->setParameter('estado', 0);}
        }
        if($id>0){
            $qb->andWhere('e.id = :id');
            $qb->setParameter('id', $id);
        }
        $qb->addOrderBy('ped.codigoPedido', 'DESC');
        $pedidos = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
		//var_dump($pedidos);die;
        $paginator = $this->get('knp_paginator');
        $limite = $this->container->getParameter('limitePaginacion');
        $pagination = $paginator->paginate(
            $pedidos,
            $request->query->getInt('page', 1),
            $limite
        );

        return $this->render('WsunBundle:pedido:index_filtro.html.twig',
            array('pagination' => $pagination));

        }

    /**
     * Creates a new pedido entity.
     *
     */
    public function newAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $rol='';
        if($this->getUser())
            $rol=$this->getUser()->getRoles()[0]->getName();
        $pedido = new Pedido();
        $pedido->setFechaCreacion(new \DateTime('now'));
        $form = $this->createForm('WsunBundle\Form\PedidoType', $pedido,array($rol));
                      
        $form->handleRequest($request);
        $pedidos = $em->getRepository('WsunBundle:Pedido')->findOneBy(array(),array('id' => 'DESC'));
        if(count($pedidos)>0){
            $codigo=$pedidos->getCodigoPedido()+1;
        }else{
            $codigo=100;
        }
        if ($form->isValid()){//$form->isSubmitted() && $form->isValid()) {
            //$fc=$form->getData()->getFechaCreacion();
            //$date = new \DateTime($fc);
            $em = $this->getDoctrine()->getManager();
            
            $pedido->setCodigoPedido($codigo);
           // $pedido->setFechaCreacion($date);
            $pedido->setUpdatedBy(-1);
            $em->persist($pedido);
            $em->flush();

            return $this->redirectToRoute('pedido_show', array('id' => $pedido->getId()));
        }

        return $this->render('WsunBundle:pedido:new.html.twig', array(
            'codigo'=>$codigo,
            'pedido' => $pedido,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a pedido entity.
     *
     */
    public function showAction(Request $request,Pedido $pedido)
    {
        $empresa=0;
		if (!is_null($pedido->getIdUsuario()->getDepartamento())){
				$empresa=$pedido->getIdUsuario()->getDepartamento()->getIdEmpresa()->getId();
		}
		if ($empresa==0){
                    $mensaje = 'No existe una empresa asociado al usuario, Verifique!!';
                    $this->session->getFlashBag()->add("status",$mensaje);
                    return $this->redirectToRoute('pedido_new');
		}
		
        $em = $this->getDoctrine()->getManager();
        if($pedido->getUpdatedBy()==-1)
        {
            $aprobador='Orden Pendiente';
        }else if($pedido->getUpdatedBy()>0)
        {
            $usuarioAprobado = $em->getRepository('WsunBundle:Usuarios')->find($pedido->getUpdatedBy());
            $aprobador=$usuarioAprobado->getUsername();
        }
        $deleteForm = $this->createDeleteForm($pedido);
        
        $pedidosDet = $em->getRepository('WsunBundle:DetallePedido')->findByIdPedido($pedido->getId());
        $paginator = $this->get('knp_paginator');
        $limite = $this->container->getParameter('limitePaginacion');
        $pagination = $paginator->paginate(
                $pedidosDet, 
                $request->query->getInt('page', 1),
                $limite
        );
        return $this->render('WsunBundle:pedido:show.html.twig', array(
            'id'=>$pedido->getId(),
            'empresa'=>$empresa,
            'aprobador'=>$aprobador,
            'pedido' => $pedido,
            'pagination' => $pagination,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing pedido entity.
     *
     */
    public function editAction(Request $request, Pedido $pedido)
    {
        $rol='';
        if($this->getUser()){
                $rol=$this->getUser()->getRoles()[0]->getName();
        }
        
        $deleteForm = $this->createDeleteForm($pedido);
        $editForm = $this->createForm('WsunBundle\Form\PedidoType', $pedido,array($rol));
        $editForm->handleRequest($request);
   
        //var_dump($editForm->getData()->getFechaCreacion());die;
        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $pedido->setUpdatedBy($this->getUser()->getId());
            $em = $this->getDoctrine()->getManager();
            $em->persist($pedido);
            $em->flush();
            //$this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pedido_edit', array('id' => $pedido->getId()));
        }

        return $this->render('WsunBundle:pedido:edit.html.twig', array(
            'pedido' => $pedido,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a pedido entity.
     *
     */
    public function deleteAction(Request $request, Pedido $pedido)
    {
        
        $em = $this->getDoctrine()->getManager();
        if($pedido->getEstadoPedido()==true){
            $mensaje = 'No se puede eliminar debido a que ya se acepto el pedido';
            $this->session->getFlashBag()->add("status",$mensaje);
            return $this->redirectToRoute('pedido_index');
        }else{

src/WsunBundle/Resources/views/pedido/edit.html.twig
{% extends 'WsunBundle:Default:index.html.twig'%}

{% block bloque1 %}
<div class="box">
    <div class="panel panel-azul">
    <fieldest>
        
    <legend class="text-center header">Edición Pedido</legend>
    {{ form_start(edit_form,{'class':"form-horizontal",'method':"POST"}) }}
        <div class="container-fluid">
        <div class="row text-justify">
            <div class="col-md-4">
                <span class="help-block text-muted small-font" > {{ form_label(edit_form.codigoPedido)}}</span>
                                {{ form_widget(edit_form.codigoPedido, { 'attr': {'readonly':'true' } }) }}
            </div>
            <div class="col-md-4">
                <span class="help-block text-muted small-font" > {{ form_label(edit_form.fechaCreacion)}}</span>
                                    {{ form_widget(edit_form.fechaCreacion) }}
            </div>
          <div class="col-md-2"><span class="help-block text-muted small-font" > Orden Sap</span>
                                    {{ form_widget(edit_form.ordenSap) }}</div>
          <div class="col-md-2"> 
          </div>
        </div>
        <div class="row ">
            {% if is_granted('ROLE_ACEPTAR_PEDIDO')%}
                   <div class="col-md-4">
                    <span class="help-block text-muted small-font" > Estado</span>
                    {{ form_widget(edit_form.estadoPedido) }}
                    </div>
            {% endif %}
           
        </div>
    </fieldset>
                {{ form_end(edit_form) }}
          <div class="col-md-3">
                <span class="help-block text-muted small-font" > </span>
                <input type="submit" class="btn btn-info" value="Edit" />
            </div>
             <div class="col-md-3">
               <span class="help-block text-muted small-font" > </span>
                 <a href="{{ path('pedido_index') }}" class="btn btn-primary btn-sm">Atras</a>

            </div>
            <div class="col-md-3">
              <span class="help-block text-muted small-font" > </span>
            <a href= "{{ path('detallepedido_index',{ 'id':pedido.id }) }}" class="btn btn-primary btn-sm">products</a>
         </div>
         <div class="col-md-3">
            <span class="help-block text-muted small-font" > </span>
                {{ form_start(delete_form) }}
                <input type="submit"  class="btn btn-info" value="Borrar">
                {{ form_end(delete_form) }}
        </div>   
        </div>
        </div>
    </div>
 
{% endblock %}

src/WsunBundle/Resources/views/pedido/index.html.twig
{% extends 'WsunBundle:Default:index.html.twig'%}

{% block bloque1 %}
<div class="box">
    {% for message in app.session.flashbag().get('status')%}
        <div class="alert alert-success">
            {{message}}
        </div>
    {% endfor%} 
    <div class="panel panel-azul">
        <div class="row">
            <div class="col-xs-6">
                <div class="selector-empresa">
                    <label class="col-sm-4 control-label">Pedido: </label>
                    <div class="col-sm-8 form-control-static">
                        <select id="selector_empresa" name="selector_empresa" class="chosen-select" required="required" tabindex="2">
                            <option disabled selected value="0">Seleccione...</option>
                            {% for key, e in empresa %}
                                <option value="{{e.id}}" >{{ e.nombreEmp }} - Cod: {{e.codigoPedido}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
				{% set rol=app.user.roles[0].role %}
					
            {% if rol!='ROLE_ACEPTAR_PEDIDO' %}
           	<a href="{{ path('pedido_new') }}"><ion-icon name="add-circle"><b>Nuevo</b></ion-icon></a>			
            {% endif %}      
            </div>
            <div class="col-xs-6">
                <div class="selector-empresa">
                    <label class="col-sm-4 control-label">Estado: </label>
                    <div class="col-sm-8 form-control-static">
                        <select id="estado" name="estado" class="chosen-select" required="required" tabindex="2">
                            <option disabled selected value="">Seleccione...</option>
                            <option  value="0">Pendiente</option>
                            <option  value="1">Aceptado</option>
                            {#% for key, e in pagination %}
                                <option value="{{e.id}}" >{{ e.codigoPedido }}({{ e.nombreEmp }})</option>
                            {% endfor %#}
                        </select>
                    </div>
                </div>
            </div>
        </div>
        
        <fieldset>
            <legend class="text-center header">LISTA DE PEDIDOS</legend>
            <div id="tabla_lista">
             <div class="count">
                <span class="label label-primary">
                Total: {{ pagination.getTotalItemCount }}
                </span>
            </div><br/>

        <table class="table table-bordered">
            <tr>
            {# sorting of properties based on query components #}
            <th>{{ knp_pagination_sortable(pagination, 'N°', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'CÓDIGO', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'EMPRESA', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'DEPARTAMENTO', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'ESTADO', '') }}</th>
           <th>{{ knp_pagination_sortable(pagination, 'FECHA CREACIÓN', '') }}</th>
           <th>{{ knp_pagination_sortable(pagination, 'ACCIONES', '') }}</th>
        </tr> 
         {% set contador= 1%}
        {% for pedido in pagination %}
            <tr {% if loop.index is odd %}class="color"{% endif %}>
                <td>{{ contador }}</td>
                <td>{{ pedido.codigoPedido }}</td>
                <td>{{ pedido.nombreEmp }}</td>
                <td>{{ pedido.nombreDep }}</td>
                <td>{% if pedido.estadoPedido %}Aprobado{% else %}Pendiente{% endif %}</td>
                <td>{{ pedido.fechaCreacion|date('Y-m-d')  }}</td> 
                <td>
                    <div class="row">
                        <div class="col-md-3">
                         <a href= "{{ path('pedido_show', { 'id': pedido.id }) }}" class="btn btn-primary btn-sm">show</a>
                        </div>
						{% if rol!='ROLE_ACEPTAR_PEDIDO' %}
                         <div class="col-md-2">
                         <a href= "{{ path('pedido_edit', { 'id': pedido.id }) }}" class="btn btn-primary btn-sm">edit</a>
                        </div>
						
                        <div class="col-md-2">
                            <div class="col-md-3"><a href ="{{path('addpedido_index',{'idPedido':pedido.id,'id' :pedido.idEmpresa |default('empresa')})}}" class="btn btn-primary btn-sm">Productos</a></div>
{#                           <a href= "{{ path('detallepedido_index',{ 'id':pedido.id,'idEmpresa':pedido.idEmpresa }) }}" class="btn btn-primary btn-sm">products</a>#}
                        </div>
						{% endif %} 
                    </div>
                </td>
            </tr>
            {% set contador= contador+1%}
        {% endfor %}
    </table>
        </div>
</fieldset>
 
  
</div></div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
    $("#selector_empresa").click(function(){
        var id=$(this).val();
        var estado = $('#estado').val();

        //var desde =$('#form_desde').val();
        //var hasta =$('#form_hasta').val();
       // var empresa_id = $('#selector_empresa').val();
        $.ajax({
            method: 'POST',
           // data: {id:id,empresa_id:empresa_id,desde:desde,hasta:hasta },
            data: {id:id,estado:estado },
            url: "{{ path('wsun_reporte_consulta_pedido_empresa') }}",
            context: document.body
        }).done(function(data) {

            $('#tabla_lista').html(data);
        });
    });
    $("#estado").change(function(){
        var estado=$(this).val();
        var id = $('#selector_empresa').val();
                //var hasta =$('#form_hasta').val();
                // var empresa_id = $('#selector_empresa').val();
                $.ajax({
                    method: 'POST',
                    // data: {id:id,empresa_id:empresa_id,desde:desde,hasta:hasta },
                    data: {id:id,estado:estado },
                    url: "{{ path('wsun_reporte_consulta_pedido_empresa') }}",
                    context: document.body
                }).done(function(data) {

                    $('#tabla_lista').html(data);
                });
            });
        });
    </script>  
{% endblock %}

src/WsunBundle/Resources/views/pedido/index_filtro.html.twig
<div class="panel panel-azul">
    {% for message in app.session.flashbag().get('status')%}
        <div class="alert alert-success">
            {{message}}
        </div>
    {% endfor%} 

        <fieldset>

             <div class="count">
                <span class="label label-primary">
                Total: {{ pagination.getTotalItemCount }}
                </span>
            </div><br/>
        <div id="tabla_lista">
        <table class="table table-bordered">
            <tr>
            {# sorting of properties based on query components #}
            <th>{{ knp_pagination_sortable(pagination, 'N°', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'CÓDIGO', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'EMPRESA', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'DEPARTAMENTO', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'ESTADO', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'FECHA CREACIÓN', '') }}</th>
            <th>{{ knp_pagination_sortable(pagination, 'ACCIONES', '') }}</th>
        </tr> 
         {% set contador= 1%}
        {% for pedido in pagination %}
            <tr {% if loop.index is odd %}class="color"{% endif %}>
                <td>{{ contador }}</td>
                <td>{{ pedido.codigoPedido }}</td>
                <td>{{ pedido.nombreEmp }}</td>
                <td>{{ pedido.nombreDep }}</td>
                <td>{% if pedido.estadoPedido %}Aprobado{% else %}Pendiente{% endif %}</td>
                <td>{{ pedido.fechaCreacion }}</td> 
                <td>
                    <div class="row">
                        <div class="col-md-3">
                         <a href= "{{ path('pedido_show', { 'id': pedido.id }) }}" class="btn btn-primary btn-sm">show</a>
                        </div>
                         <div class="col-md-2">
                         <a href= "{{ path('pedido_edit', { 'id': pedido.id }) }}" class="btn btn-primary btn-sm">edit</a>
                        </div>
                        <div class="col-md-2">
                             <a href= "{{ path('detallepedido_index',{ 'id':pedido.id,'idEmpresa':pedido.idEmpresa }) }}" class="btn btn-primary btn-sm">products</a>
                        </div>
                    </div>
                </td>
            </tr>
            {% set contador= contador+1%}
        {% endfor %}
    </table>
        </div>
</fieldset>
  {#<a href="{{ path('pedido_new') }}"> <span class="glyphicon glyphicon-file"> Nuevo</span></a>#}
</div></div>

src/WsunBundle/Resources/views/pedido/new.html.twig
{% extends 'WsunBundle:Default:index.html.twig'%}

{% block bloque1 %}
<div class="box">
    <div class="panel panel-azul">
	  {% for message in app.session.flashbag().get('status')%}
        <div class="alert alert-success">
            {{message}}
        </div>
    {% endfor%}
    <fieldest>
        
    <legend class="text-center header">Pedido</legend>
    {{ form_start(form,{'class':"form-horizontal",'method':"POST"}) }}
        <div class="container-fluid">
        <div class="row text-justify">
            <div class="col-md-4">
                <span class="help-block text-muted small-font" > {{ form_label(form.codigoPedido)}}</span>
                                {{ form_widget(form.codigoPedido, { 'attr': {'value':codigo,'placeholder': 'Escribe el código del pedido','readonly':'true' } }) }}
            </div>
            <div class="col-md-4">
                <span class="help-block text-muted small-font" > {{ form_label(form.fechaCreacion)}}</span>
                                    {{ form_widget(form.fechaCreacion) }}
            </div>
          <div class="col-md-2"><span class="help-block text-muted small-font" > Orden Sap</span>
                                    {{ form_widget(form.ordenSap) }}</div>
          <div class="col-md-2"> 
          </div>
        </div>
        <div class="row ">
            {% if is_granted('ROLE_ACEPTAR_PEDIDO')%}
            <div class="col-md-4">
                <span class="help-block text-muted small-font" > Estado</span>
                {{ form_widget(form.estadoPedido) }}
             </div>
            {% endif %}
            <div class="col-md-4">
                <span class="help-block text-muted small-font" > </span>
                <input type="submit" class="btn btn-info" value="Create" />
            </div>
             <div class="col-md-4">
               <span class="help-block text-muted small-font" > </span>
                 <a href="{{ path('pedido_index') }}" class="btn btn-primary btn-sm">Atras</a>

            </div>
        </div>
    </fieldset>
                {{ form_end(form) }}
            </div>
        </div>
    </div>


{% endblock %}